/**
 * Store all GQL queries in central file
 */

import { AXIOS_REFRESH_TOKEN, AXIOS_VALID_ACCOUNT, AXIOS_GET_USERS, AXIOS_GET_USER, AXIOS_VERIFY_USER_TOKEN, AXIOS_GET_A_COMPANY_USERS, AXIOS_LOGIN_USER, AXIOS_REGISTER_USER, AXIOS_VERIFY_USER_REGISTER_ACCOUNT, AXIOS_UPDATE_USER, AXIOS_GET_CURRENT_USER, AXIOS_SEARCH_USERS, AXIOS_GET_USER_CONF, } from './users.axios-queries.js'

// import { AXIOS_CHECK_COMPANY, AXIOS_GET_COMPANY, AXIOS_GET_COMPANIES, AXIOS_INFINITE_SCROLL_COMPANIES, AXIOS_SEARCH_ANY_ON_COLLEAGUES, } from './departments.axios-queries.js'
import { AXIOS_GET_DEPARTMENTS, AXIOS_GET_PLACECHIEFS_BY_DEPARTMENTS, AXIOS_GET_TAXTYPES, AXIOS_GET_NEIGHBORHOODS_BY_PLACECHIEDID, AXIOS_GET_TAXCENTERS_BY_NEIGHBORDHOODID, } from './departments.axios-queries.js'

export {
  // USERS QUERIES AND MUTATIONS EXPORTS
  AXIOS_REFRESH_TOKEN, AXIOS_VALID_ACCOUNT, AXIOS_GET_USERS, AXIOS_GET_USER, AXIOS_VERIFY_USER_TOKEN, AXIOS_GET_A_COMPANY_USERS, AXIOS_LOGIN_USER, AXIOS_REGISTER_USER, AXIOS_VERIFY_USER_REGISTER_ACCOUNT, AXIOS_UPDATE_USER, AXIOS_GET_CURRENT_USER, AXIOS_SEARCH_USERS, AXIOS_GET_USER_CONF,

  // DEPARTMENTS
  AXIOS_GET_DEPARTMENTS, AXIOS_GET_PLACECHIEFS_BY_DEPARTMENTS, AXIOS_GET_TAXTYPES, AXIOS_GET_NEIGHBORHOODS_BY_PLACECHIEDID, AXIOS_GET_TAXCENTERS_BY_NEIGHBORDHOODID,

}
